-d /home/merllab/Desktop/HDMI_take2/pll/impl/gwsynthesis/pll.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cfg /home/merllab/Desktop/HDMI_take2/pll/impl/pnr/device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
